Afferay/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Product/', include('Product.urls')),
    path('Contact/', include('Contact.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

Product/urls.py
from . import views
from django.urls import path

urlpatterns = [
	
	    path('',views.HomePage.as_view(),name="Homepage"),
	    path('Create/',views.product_form,name='Createproduct'),
	    path(r'Listing/',views.product_list, name='product_list'),

	   	path(r'Listingcrops/',views.photo_list, name='product_list'),

	    path(r'product_detailing/<slug>/',views.product_detail, name='product_detail'),
	    path(r'Filter/', views.Filter, name='Filter'),
	   	path(r'product_update/<slug>/',views.product_update, name='product_update'),
	   	path(r'product_delete/<slug>/',views.product_delete, name='product_delete'),
	   	path('Searchproduit/',views.Search,name='Searchproduit'),



]

Product/models.py

from __future__ import unicode_literals

from django.db import models

# Create your models here.


from django.utils.text import slugify
from django.urls import reverse






class Product(models.Model):


	CATEGORY =  (('','_______________________Voiture _______________________'),
				 ('Citroen','Citroen'),
				 ('Cat cat','Cat cat'),
				 ('Renault 19','Renault 19'),)

	Ville   = (('','_______________________Ville _______________________'),
		       ('Agadir','Agadir'),
		       ('Rabat','Rabat'),
		       ('Casablanca','Casablanca'),
		       ('Tanger','Tanger'),
		      )

	


	Nom_Produit              =models.CharField(max_length=200,blank=True,null=True)

	Description      =models.TextField(blank=True,null=True)

	Category         =models.CharField(max_length=600,choices=CATEGORY)

	Ville            =models.CharField(max_length=600,choices=Ville)

	Created          =models.DateTimeField(auto_now_add=True)

	updated_at       =models.DateTimeField(auto_now=True)


	slug             =models.SlugField(null=True,blank=True)

	Price            =models.CharField(max_length=200,blank=True,null=True)


	Nom_Annonceur    =models.CharField(max_length=200,blank=True,null=True)
	phone_Number     =models.PositiveIntegerField(default=0)









	def __str__(self):

		return self.Nom_Produit


	def get_absolute_url(self):
	    return reverse("product_detail", kwargs={"slug": self.slug})

	class Meta:
	    ordering = ['-Created']

	def _get_unique_slug(self):
	    slug = slugify(self.Nom_Produit)
	    unique_slug = slug
	    num = 1
	    while Product.objects.filter(slug=unique_slug).exists():
	        unique_slug = '{}-{}'.format(slug, num)
	        num += 1
	    return unique_slug

	def save(self, *args, **kwargs):
	    if not self.slug:
	        self.slug = self._get_unique_slug()
	    super(Product, self).save()



class Images(models.Model):
	product   = models.ForeignKey(Product,blank=True,null=True,on_delete=models.CASCADE)
	image    = models.ImageField(upload_to='crop',blank=True)

	def __str__(self):
		return "Addition image"


Product/forms.py
from .models import Product,Images
from django import forms
from PIL import Image
from django.forms import ModelForm

class Productform(forms.ModelForm):


    class Meta:

          model = Product
          fields =('Category','Ville','Nom_Produit','Description','Price','Nom_Annonceur','phone_Number')
          labels ={
                  'Nom_Annonceur':'Available Nom de l annonceur ',
                  'phone_Number':'Available phonenumber',
                 
                }
          widgets = {
            'Nom Annonceur': forms.TextInput(attrs={'placeholder': 'Separate item colors with comma e.g red,black,green'}),
            'phoneNumber': forms.TextInput(attrs={'placeholder': 'Separate item size with comma e.g 2,5 or X,ML,M'}),
        }

         

class AdditionImageForm(forms.ModelForm):

    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Images
        fields = ('product',
                  'image',
                  'x',
                  'y',
                  'width',
                  'height')

    def save(self):
        photo = super(AdditionImageForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.file)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((400, 400), Image.ANTIALIAS)
        resized_image.save(photo.file.path)

        return photo

Product/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import (View,TemplateView,
	                              ListView,DetailView,
	                              CreateView,DeleteView,UpdateView)

from django.http import HttpResponse
from .forms import Productform,AdditionImageForm
from Product.models import Product,Images
from django.forms.models import modelformset_factory
from django.shortcuts import render, get_object_or_404, redirect
from .filters import UserFilter
from django.core.paginator import Paginator



class HomePage(TemplateView):

	template_name ="Product/home.html"



def product_form(request):

	photos = Images.objects.all()

	imageformset =modelformset_factory(Images,fields=('image',),extra=2)
	if request.method =='POST':
			form    =Productform(request.POST, request.FILES)
			formset =imageformset(request.POST or None,request.FILES or None)
			if form.is_valid() and formset.is_valid():
				product = form.save(commit=False)
				product.user = request.user
				product.save() 

				for f in formset:

					try:
						photo =Images(product=product,image =f.cleaned_data['image'])
						photo.save()
					except Exception as e:
						break
				return redirect(product.get_absolute_url())

	else:
			form =Productform()
			formset =imageformset(queryset=Images.objects.none())


	context ={"form":form,"formset":formset,'photos': photos}
	context['header'] ="Upload your products"

	return render(request, "Product/form.html",context)






def product_list(request):
    categories = Product.objects.all()
    paginator = Paginator(categories, 2)
    page = request.GET.get('page')
    contacts = paginator.get_page(page)

    context = { "categories": categories,"contacts":contacts }
    return render(request, "Product/product_list.html", context)


def product_detail(request, slug=None):
    proddetail = get_object_or_404(Product, slug=slug)
    context = { "proddetail": proddetail,}
    return render(request, "Product/product_detail.html", context)


def Filter(request):
    product_list = Product.objects.all()
    user_filter = UserFilter(request.GET, queryset=product_list)
    return render(request, 'Product/p_list.html', {'filter': user_filter})

def product_update(request, slug=None):

	photos = Images.objects.all()
	instance = get_object_or_404(Product, slug=slug)
	imageformset =modelformset_factory(Images,fields=('image',),extra=2)
	if request.method =='POST':
			form    =Productform(request.POST, request.FILES)
			formset =imageformset(request.POST or None,request.FILES or None)
			if form.is_valid() and formset.is_valid():
				product = form.save(commit=False)
				product.user = request.user
				product.save() 

				for f in formset:

					try:
						photo =Images(product=product,image =f.cleaned_data['image'])
						photo.save()
					except Exception as e:
						break
				return redirect(product.get_absolute_url())

	else:
			form =Productform()
			formset =imageformset(queryset=Images.objects.none())


	context ={"form":form,"formset":formset,}
	context['header'] ="Upload your products"

	return render(request, "Product/form.html",context)


def product_delete(request, slug=None):
    product = get_object_or_404(Product, slug=slug)
    product.delete() 
    return redirect('product_list')

from django.db.models import Q

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def Search(request):

		queryset = Product.objects.all()
		query = request.GET.get("q")   
		if query:
		    queryset = queryset.filter(
		        Q(Nom_Produit__contains=query))

		paginator = Paginator(queryset, 12)
		page = request.GET.get("page")
		try:
		    query_list = paginator.page(page)
		except PageNotAnInteger:
		    query_list = paginator.page(1)
		except EmptyPage:
		    query_list = paginator.page(paginator.num_pages)

		context = { "query_list": query_list }
		return render(request, "Product/productsearch.html", context)

from django.shortcuts import render, redirect

from .models import Images
from .forms import AdditionImageForm


def photo_list(request):
    photos = Images.objects.all()
    if request.method == 'POST':
        form = AdditionImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('photo_list')
    else:
        form = AdditionImageForm()
    return render(request, 'Product/photo_list.html', {'form': form, 'photos': photos})



Product/templates/Product/base.html
{% load  staticfiles %}
{% load crispy_forms_tags %}

{% load static %}

<!DOCTYPE html>
<html>
<head>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>AfferayMaroc</title>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

      <link href="{% static 'css/cropper.min.css' %}" rel="stylesheet">

</head>
<body   style="background:rgba(0,0,0,0.1);">
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a  href="{% url "Homepage" %}">Afferay Maroc</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
           <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a  href="{% url "Createproduct" %}">Create Annonce</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            
           <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a  href="{% url "contacts_view" %}">Contacts</a>
                    <nav class="navbar navbar-expand-lg navbar-light bg-light">

          <div style="float: right;">
            <form method='GET' action=''>
                <input type='text' name='q' placeholder='Search' value='{{ request.GET.q }}'/>
                <input class="btn btn-primary" type='submit' value='Search' />
            </form>
          </div>
<hr>

      
      </nav>

    </div>

  		
    

    <div class="mt-2">
      {% block slider %}

      {% endblock%}
    </div>
      <div class="mt-2">

        {% block javascript %}     
        {% endblock%}
      </div>



    
    <div class=" mx-1 row">
        
        <div class="col-sm-12">
          <div class="row">
            <div class="col-sm-1">
                
            </div>
            <div class="col-sm-10">
                {% block body %}

                {% endblock %}
            </div>
            <div class="col-sm-1">
               
            </div>
             
          </div>
        </div>

    </div>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
      <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/cropper.min.js' %}"></script>
    <div class="">
      {% block adds %}

      {% endblock%}
    </div>
     
  	</div>
  

      {% include "Product/footer.html" %}


</body>

Product/templates/Product/footer.html
<!-- Footer -->
<footer class="page-footer font-small blue-grey lighten-5">

  <div style="background-color: #21d192;">
    <div class="container">

      <!-- Grid row-->
      <div class="row py-4 d-flex align-items-center">

        <!-- Grid column -->
        <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
          <h6 class="mb-0">Get connected with us on social networks!</h6>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-6 col-lg-7 text-center text-md-right">

          <!-- Facebook -->
          <a class="fb-ic">
            <i class="fab fa-facebook-f white-text mr-4"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic">
            <i class="fab fa-twitter white-text mr-4"> </i>
          </a>
          <!-- Google +-->
          <a class="gplus-ic">
            <i class="fab fa-google-plus-g white-text mr-4"> </i>
          </a>
          <!--Linkedin -->
          <a class="li-ic">
            <i class="fab fa-linkedin-in white-text mr-4"> </i>
          </a>
          <!--Instagram-->
          <a class="ins-ic">
            <i class="fab fa-instagram white-text"> </i>
          </a>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row-->

    </div>
  </div>

  <!-- Footer Links -->
  <div class="container text-center text-md-left mt-5">

    <!-- Grid row -->
    <div class="row mt-3 dark-grey-text">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-4 col-xl-3 mb-4">

        <!-- Content -->
        <h6 class="text-uppercase font-weight-bold">Company name</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>Here you can use rows and columns to organize your footer content. Lorem ipsum dolor sit amet,
          consectetur
          adipisicing elit.</p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Products</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a class="dark-grey-text" href="#!">MDBootstrap</a>
        </p>
        <p>
          <a class="dark-grey-text" href="#!">MDWordPress</a>
        </p>
        <p>
          <a class="dark-grey-text" href="#!">BrandFlow</a>
        </p>
        <p>
          <a class="dark-grey-text" href="#!">Bootstrap Angular</a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Useful links</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a class="dark-grey-text" href="#!">Your Account</a>
        </p>
        <p>
          <a class="dark-grey-text" href="#!">Become an Affiliate</a>
        </p>
        <p>
          <a class="dark-grey-text" href="#!">Shipping Rates</a>
        </p>
        <p>
          <a class="dark-grey-text" href="#!">Help</a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Contact</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <i class="fas fa-home mr-3"></i> Zaouit ech cheikh,</p>
        <p>
          <i class="fas fa-envelope mr-3"></i> mohammed.aabi@gmail.com</p>
        <p>
          <i class="fas fa-phone mr-3"></i> +212600421951</p>
        

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center text-black-50 py-3">© 30/11/2019 Copyright:
    <a class="dark-grey-text" href="https://mdbootstrap.com/education/bootstrap/"> www.AfferayMaroc.ma</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

Product/templates/Product/form.html

{% extends "Product/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% load thumbnail %}
{% load cropping %}
 


  <!-- FORM TO UPLOAD THE IMAGES -->
  
    

  
      
{% block slider %}
 <h1 class="page-header">Creation Annonce</h1>

  <!-- FORM TO UPLOAD THE IMAGES -->
    <div class='row'>
     <div class="col-4"> 
      <div class="card">
       <div class="card-body">
            <form method="post" enctype="multipart/form-data" id="formUpload">{% csrf_token %}
                  {{ form|crispy}}
                  {{ formset.as_p }}
                  <br>
                  <input class="btn btn-success" type="submit" value='Submit'>
            </form>
        </div>
      </div>
     </div>
    </div>


{% block simo %} {% endblock %}
  
 

  

{% endblock %}

Product/templates/Product/home.html
{% extends "Product/base.html" %}


{% block slider %}

 			<h1>hello this site is from Afferay Maroc if you need in help call me okay brother  </h1>

{% endblock%}


Product/templates/Product/p_list.html
{% extends 'Product/base.html' %}

{% block slider %}
  <form method="get">
    {{ filter.form.as_p }}
    <button type="submit">Search</button>
  </form>
  <ul>
  {% for user in filter.qs %}
    <li>{{ user.Nom_Produit }} - {{ user.Description }}</li>
  {% empty %}
   <li> Not existe that product </li>
  {% endfor %}
  </ul>
{% endblock %}

Product/templates/Product/photo_list.html
{% extends 'Product/base.html' %}

{% block javascript %}
  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_file").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 200,
          minCropBoxHeight: 200,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>
{% endblock %}

{% block content  %}
      <h1 class="page-header">Album</h1>

      <!-- FORM TO UPLOAD THE IMAGES -->
      <form method="post" enctype="multipart/form-data" id="formUpload">
        {% csrf_token %}
        {{ form }}
      </form>

      <!-- MODAL TO CROP THE IMAGE -->
      <div class="modal fade" id="modalCrop">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <h4 class="modal-title">Crop the photo</h4>
            </div>
            <div class="modal-body">
              <img src="" id="image" style="max-width: 100%;">
            </div>
            <div class="modal-footer">
              <div class="btn-group pull-left" role="group">
                <button type="button" class="btn btn-default js-zoom-in">
                  <span class="glyphicon glyphicon-zoom-in"></span>
                </button>
                <button type="button" class="btn btn-default js-zoom-out">
                  <span class="glyphicon glyphicon-zoom-out"></span>
                </button>
              </div>
              <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
              <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
            </div>
          </div>
        </div>
      </div>

      <!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
      <div class="row" style="margin-top: 20px">
        {% for photo in photos %}
          <div class="col-sm-4 col-md-3">
            <img src="{{ photo.images.url }}" class="thumbnail">
          </div>
        {% endfor %}
      </div>

{% endblock %}

Product/templates/Product/product_detail.html
{% extends "Product/base.html" %}
{% block slider %}

  <div class="col-sm-3 text-center p-2 my-1">


     <div class="p-2 my-2 rounded" style="box-shadow:2px 2px 2px 2px gray;" id="related_item">
      
       <p><b>

          <span style="color:red; background-color:yellow;">
                {{proddetail.Nom_Produit}}

          </span> 
      <div class="row gallery">
        {% for p in proddetail.images_set.all %}
          <div class="col-md-3">
                      <img src="{{ p.image.url }}"  class="thumbnail" style="max-width: 100%;">

          </div>
        {% endfor %}
      </div>
                     <p> {{proddetail.Price}}</p>

     </div>
        </b></p>
     </div>
    
  </div>



{% endblock %}


Product/templates/Product/product_list.html
{% extends 'Product/base.html' %}

{% block javascript %}
  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_file").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 200,
          minCropBoxHeight: 200,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>
{% endblock %}

{% block content %}
  <h1 class="page-header">Album</h1>

  <!-- FORM TO UPLOAD THE IMAGES -->
  <form method="post" enctype="multipart/form-data" id="formUpload">
    {% csrf_token %}
    {{ form }}
  </form>

  <!-- MODAL TO CROP THE IMAGE -->
  <div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Crop the photo</h4>
        </div>
        <div class="modal-body">
          <img src="" id="image" style="max-width: 100%;">
        </div>
        <div class="modal-footer">
          <div class="btn-group pull-left" role="group">
            <button type="button" class="btn btn-default js-zoom-in">
              <span class="glyphicon glyphicon-zoom-in"></span>
            </button>
            <button type="button" class="btn btn-default js-zoom-out">
              <span class="glyphicon glyphicon-zoom-out"></span>
            </button>
          </div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
          <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
        </div>
      </div>
    </div>
  </div>

  <!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
  <div class="row" style="margin-top: 20px">
    {% for photo in photos %}
      <div class="col-sm-4 col-md-3">
        <img src="{{ photo.file.url }}" class="thumbnail">
      </div>
    {% endfor %}
  </div>

{% endblock %}

Product/templates/Product/productsearch.html
{% extends "Product/base.html" %}


{% block slider %}
      


    <hr>

    <hr>

    {% for product in query_list %}
          {% if request.GET.q %}
           <div class="list-group">
              <div class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between">
                  <small>{{ produit.Nom_Produit }}  <b>
                  </b></small>
                      <small>{{ produit.Description }}  <b>
                  </b></small>
                </div>
              </div>
            </div>

          {% endif %}
    {% empty %}
      <h1>No product for this name </h1>
    {% endfor %}


{% endblock  %}